package osadnicizkatanu.platno;

import java.awt.Font;
import java.awt.Point;
import javax.swing.JOptionPane;
import osadnicizkatanu.hra.Hrac;
import osadnicizkatanu.hra.HracPanel;
import osadnicizkatanu.hra.prislusenstvo.Kocka;
import osadnicizkatanu.hra.prislusenstvo.VykreslovacCesty;
import osadnicizkatanu.hra.prislusenstvo.VykreslovacObce;
import osadnicizkatanu.surovina.Drevo;
import osadnicizkatanu.surovina.Kamen;
import osadnicizkatanu.surovina.Obilie;
import osadnicizkatanu.surovina.Ovca;
import osadnicizkatanu.surovina.Tehla;
import osadnicizkatanu.surovina.VykreslovacSuroviny;

/**
 * Trieda reprezentujuca hlavne hracie okno hry Osadnici z Katanu
 * @author Adam
 */
public class HlavneOkno extends javax.swing.JFrame {
    private Kocka kocka;
    private final Hrac hrac1;
    private final Hrac hrac2;
    private Hrac hracNaRade;
    private Hrac hracNehrajuci; 
    private int tah;
    
    /**
     * Konstruktor vytvori hlavne okno s dvomi hracmi
     * @param hrac1 prvy hrac
     * @param hrac2 druhy hrac
     */
    public HlavneOkno(Hrac hrac1, Hrac hrac2) {
        this.hrac1 = hrac1;
        this.hrac2 = hrac2;
        
        this.initComponents();

        this.kocka = new Kocka();
        this.hrac1.setPanel(this.pnlHrac1);
        this.hrac2.setPanel(this.pnlHrac2);
        
        this.hracNaRade = this.hrac1;
        this.hracNehrajuci = this.hrac2;
        
        this.lyrPlochaPrePridavanie.setPlochaPreCesty(false);
        this.lyrPlochaPrePridavanie.setPlochaPreDediny(false);
        this.lyrPlochaPrePridavanie.setPlochaPreMesta(false);
        
        this.tah = 1;
        
        this.pnlHrac1.aktualizujPocetBodov();
        this.pnlHrac2.aktualizujPocetBodov();
        
        this.pnlHrac1.aktualizujPocitadlaSurovin();
        this.pnlHrac1.aktualizujPocitadlaPrislusenstva();
        this.pnlHrac1.setStlacitelnostKupovacichTlacidiel(false);

        
        this.pnlHrac2.setStlacitelnostKupovacichTlacidiel(false);     
        this.pnlHrac2.zneviditelniPocitadlaSurovin();
        this.pnlHrac2.zneviditelniPocitadlaPrislusenstva();
        
        this.setVisible(true);
        JOptionPane.showMessageDialog(this, "Hra sa začína!\n" + this.hrac1.getMeno() + " hádže kockou.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        btnHodKockou = new javax.swing.JButton();
        lblSucetHodov = new javax.swing.JLabel();
        this.lblSucetHodov.setFont(new Font("Serif", Font.BOLD, 20));
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lyrPlochaCisla = new HraciaPlochaCisla(4, 5, 35);
        lyrHraciaPlocha = new HraciaPlocha(4, 5, 100, this.lyrPlochaCisla);
        lyrPlochaPrePridavanie = new PlochaPrePridavanie(9, 11, 50, this.lyrHraciaPlocha);
        pnlHrac1 = new osadnicizkatanu.hra.HracPanel();
        cmpDrevo1 = new VykreslovacSuroviny(new Drevo(), 0, 0, "male");
        cmpTehla1 = new VykreslovacSuroviny(new Tehla(), 0, 0, "male");
        cmpObilie1 = new VykreslovacSuroviny(new Obilie(), 0, 0, "male");
        cmpOvca1 = new VykreslovacSuroviny(new Ovca(), 0, 0, "male");
        cmpKamen1 = new VykreslovacSuroviny(new Kamen(), 0, 0, "male");
        lblDrevo1 = new javax.swing.JLabel();
        this.lblDrevo1.setFont(new Font("Serif", Font.BOLD, 30));
        lblTehla1 = new javax.swing.JLabel();
        this.lblTehla1.setFont(new Font("Serif", Font.BOLD, 30));
        lblObilie1 = new javax.swing.JLabel();
        this.lblObilie1.setFont(new Font("Serif", Font.BOLD, 30));
        lblOvca1 = new javax.swing.JLabel();
        this.lblOvca1.setFont(new Font("Serif", Font.BOLD, 30));
        lblKamen1 = new javax.swing.JLabel();
        this.lblKamen1.setFont(new Font("Serif", Font.BOLD, 30));
        jSeparator1 = new javax.swing.JSeparator();
        btnKupCestu1 = new javax.swing.JButton();
        btnKupDedinu1 = new javax.swing.JButton();
        btnKupMesto1 = new javax.swing.JButton();
        vykreslovacObce1 = new VykreslovacObce(this.hrac1, "mesto");
        vykreslovacObce2 = new VykreslovacObce(this.hrac1, "dedina");
        vykreslovacCesty1 = new VykreslovacCesty(this.hrac1);
        lblCesty1 = new javax.swing.JLabel();
        this.lblCesty1.setFont(new Font("Serif", Font.BOLD, 30));
        lblDediny1 = new javax.swing.JLabel();
        this.lblDediny1.setFont(new Font("Serif", Font.BOLD, 30));
        lblMesta1 = new javax.swing.JLabel();
        this.lblMesta1.setFont(new Font("Serif", Font.BOLD, 30));
        drevoCesta1 = new VykreslovacSuroviny(new Drevo(), 0, 0, "male");
        tehlaCesta1 = new VykreslovacSuroviny(new Tehla(), 0, 0, "male");
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        drevoDedina1 = new VykreslovacSuroviny(new Drevo(), 0, 0, "male");
        tehlaDedina1 = new VykreslovacSuroviny(new Tehla(), 0, 0, "male");
        ovcaDedina1 = new VykreslovacSuroviny(new Ovca(), 0, 0, "male");
        obilieDedina1 = new VykreslovacSuroviny(new Obilie(), 0, 0, "male");
        kamen1mesto1 = new VykreslovacSuroviny(new Kamen(), 0, 0, "male");
        kamen2mesto1 = new VykreslovacSuroviny(new Kamen(), 0, 0, "male");
        kamen3mesto1 = new VykreslovacSuroviny(new Kamen(),  0, 0, "male");
        obilie1mesto1 = new VykreslovacSuroviny(new Obilie(),0, 0, "male");
        obilie2mesto1 = new VykreslovacSuroviny(new Obilie(), 0, 0, "male");
        btnPrepniHraca = new javax.swing.JButton();
        pnlHrac2 = new osadnicizkatanu.hra.HracPanel();
        cmpDrevo2 = new VykreslovacSuroviny(new Drevo(), 0, 0, "male");
        cmpTehla2 = new VykreslovacSuroviny(new Tehla(), 0, 0, "male");
        cmpObilie2 = new VykreslovacSuroviny(new Obilie(), 0, 0, "male");
        cmpOvca2 = new VykreslovacSuroviny(new Ovca(), 0, 0, "male");
        cmpKamen2 = new VykreslovacSuroviny(new Kamen(), 0, 0, "male");
        lblDrevo2 = new javax.swing.JLabel();
        this.lblDrevo2.setFont(new Font("Serif", Font.BOLD, 30));
        lblTehla2 = new javax.swing.JLabel();
        this.lblTehla2.setFont(new Font("Serif", Font.BOLD, 30));
        lblObilie2 = new javax.swing.JLabel();
        this.lblObilie2.setFont(new Font("Serif", Font.BOLD, 30));
        lblOvca2 = new javax.swing.JLabel();
        this.lblOvca2.setFont(new Font("Serif", Font.BOLD, 30));
        lblKamen2 = new javax.swing.JLabel();
        this.lblKamen2.setFont(new Font("Serif", Font.BOLD, 30));
        jSeparator2 = new javax.swing.JSeparator();
        btnKupCestu2 = new javax.swing.JButton();
        btnKupDedinu2 = new javax.swing.JButton();
        btnKupMesto2 = new javax.swing.JButton();
        vykreslovacObce3 = new VykreslovacObce(this.hrac2, "mesto");
        vykreslovacObce4 = new VykreslovacObce(this.hrac2, "dedina");
        vykreslovacCesty2 = new VykreslovacCesty(this.hrac2);
        lblCesty2 = new javax.swing.JLabel();
        this.lblCesty2.setFont(new Font("Serif", Font.BOLD, 30));
        lblDediny2 = new javax.swing.JLabel();
        this.lblDediny2.setFont(new Font("Serif", Font.BOLD, 30));
        lblMesta2 = new javax.swing.JLabel();
        this.lblMesta2.setFont(new Font("Serif", Font.BOLD, 30));
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        drevoCesta2 = new VykreslovacSuroviny(new Drevo(), 0, 0, "male");
        tehlaCesta2 = new VykreslovacSuroviny(new Tehla(), 0, 0, "male");
        drevoDedina2 = new VykreslovacSuroviny(new Drevo(), 0, 0, "male");
        tehlaDedina2 = new VykreslovacSuroviny(new Tehla(), 0, 0, "male");
        ovcaDedina2 = new VykreslovacSuroviny(new Ovca(), 0, 0, "male");
        obilieDedina2 = new VykreslovacSuroviny(new Obilie(), 0, 0, "male");
        obilie1mesto2 = new VykreslovacSuroviny(new Obilie(), 0, 0, "male");
        obilie2mesto2 = new VykreslovacSuroviny(new Obilie(), 0, 0, "male");
        kamen1mesto2 = new VykreslovacSuroviny(new Kamen(), 0, 0, "male");
        kamen2mesto2 = new VykreslovacSuroviny(new Kamen(), 0, 0, "male");
        kamen3mesto2 = new VykreslovacSuroviny(new Kamen(), 0, 0, "male");
        lblPocetBodov1 = new javax.swing.JLabel();
        this.lblPocetBodov1.setFont(new Font("Serif", Font.BOLD, 20));
        lblPocetBodov2 = new javax.swing.JLabel();
        this.lblPocetBodov2.setFont(new Font("Serif", Font.BOLD, 20));

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 760));
        setMinimumSize(new java.awt.Dimension(1366, 760));
        setPreferredSize(new java.awt.Dimension(1366, 760));

        btnHodKockou.setText("Hoď kockou");
        btnHodKockou.setToolTipText("");
        btnHodKockou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHodKockouActionPerformed(evt);
            }
        });

        lblSucetHodov.setText("Zatiaľ si nehodil");

        jLayeredPane2.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane2.setMaximumSize(new java.awt.Dimension(450, 550));
        jLayeredPane2.setMinimumSize(new java.awt.Dimension(450, 550));

        lyrPlochaCisla.setMaximumSize(new java.awt.Dimension(400, 500));
        lyrPlochaCisla.setMinimumSize(new java.awt.Dimension(400, 500));
        lyrPlochaCisla.setOpaque(false);
        lyrPlochaCisla.setLayout(new java.awt.GridLayout(5, 4));

        lyrHraciaPlocha.setMaximumSize(new java.awt.Dimension(400, 500));
        lyrHraciaPlocha.setMinimumSize(new java.awt.Dimension(400, 500));
        lyrHraciaPlocha.setPreferredSize(new java.awt.Dimension(400, 500));
        lyrHraciaPlocha.setLayout(new java.awt.GridLayout(5, 4));

        lyrPlochaPrePridavanie.setMaximumSize(new java.awt.Dimension(450, 550));
        lyrPlochaPrePridavanie.setMinimumSize(new java.awt.Dimension(450, 550));
        lyrPlochaPrePridavanie.setOpaque(false);
        lyrPlochaPrePridavanie.setPreferredSize(new java.awt.Dimension(450, 550));
        lyrPlochaPrePridavanie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lyrPlochaPrePridavanieMouseClicked(evt);
            }
        });
        lyrPlochaPrePridavanie.setLayout(new java.awt.GridLayout(11, 9));

        jLayeredPane2.setLayer(lyrPlochaCisla, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane2.setLayer(lyrHraciaPlocha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lyrPlochaPrePridavanie, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lyrPlochaCisla, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap(24, Short.MAX_VALUE)
                    .addComponent(lyrHraciaPlocha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(27, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lyrPlochaPrePridavanie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lyrPlochaCisla, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(lyrHraciaPlocha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(25, Short.MAX_VALUE)))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lyrPlochaPrePridavanie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        this.pnlHrac1 = new HracPanel(this.hrac1, this,
            this.lblDrevo1, this.lblTehla1, this.lblObilie1, this.lblOvca1, this.lblKamen1,      
            this.lblCesty1, this.lblDediny1, this.lblMesta1,       
            this.btnKupCestu1, this.btnKupDedinu1, this.btnKupMesto1,     
            this.lblPocetBodov1);

        lblDrevo1.setText("jLabel1");

        lblTehla1.setText("jLabel2");

        lblObilie1.setText("jLabel3");

        lblOvca1.setText("jLabel4");

        lblKamen1.setText("jLabel5");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnKupCestu1.setText("Kup cestu");
        btnKupCestu1.setMaximumSize(new java.awt.Dimension(100, 30));
        btnKupCestu1.setMinimumSize(new java.awt.Dimension(100, 30));
        btnKupCestu1.setPreferredSize(new java.awt.Dimension(100, 30));
        btnKupCestu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKupCestu1ActionPerformed(evt);
            }
        });

        btnKupDedinu1.setText("Kup dedinu");
        btnKupDedinu1.setMaximumSize(new java.awt.Dimension(100, 30));
        btnKupDedinu1.setMinimumSize(new java.awt.Dimension(100, 30));
        btnKupDedinu1.setPreferredSize(new java.awt.Dimension(100, 30));
        btnKupDedinu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKupDedinu1ActionPerformed(evt);
            }
        });

        btnKupMesto1.setText("Kup mesto");
        btnKupMesto1.setMaximumSize(new java.awt.Dimension(100, 30));
        btnKupMesto1.setMinimumSize(new java.awt.Dimension(100, 30));
        btnKupMesto1.setPreferredSize(new java.awt.Dimension(100, 30));
        btnKupMesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKupMesto1ActionPerformed(evt);
            }
        });

        lblCesty1.setText("jLabel1");

        lblDediny1.setText("jLabel2");

        lblMesta1.setText("jLabel3");

        javax.swing.GroupLayout pnlHrac1Layout = new javax.swing.GroupLayout(pnlHrac1);
        pnlHrac1.setLayout(pnlHrac1Layout);
        pnlHrac1Layout.setHorizontalGroup(
            pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHrac1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmpOvca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmpObilie1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmpDrevo1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(cmpTehla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObilie1)
                            .addComponent(lblOvca1)
                            .addComponent(lblDrevo1)
                            .addComponent(lblTehla1)))
                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                        .addComponent(cmpKamen1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKamen1)))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKupDedinu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlHrac1Layout.createSequentialGroup()
                                .addComponent(vykreslovacObce2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDediny1)))
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHrac1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(drevoDedina1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(tehlaDedina1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHrac1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(ovcaDedina1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(obilieDedina1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                        .addComponent(btnKupMesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(obilie1mesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obilie2mesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                        .addComponent(vykreslovacObce1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMesta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kamen1mesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kamen2mesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kamen3mesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlHrac1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(vykreslovacCesty1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCesty1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnKupCestu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(drevoCesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tehlaCesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        pnlHrac1Layout.setVerticalGroup(
            pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHrac1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDrevo1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(cmpDrevo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTehla1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(cmpTehla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblObilie1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(cmpObilie1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOvca1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(cmpOvca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmpKamen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKamen1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(pnlHrac1Layout.createSequentialGroup()
                                .addComponent(btnKupCestu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(drevoCesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tehlaCesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(vykreslovacCesty1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCesty1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                                        .addComponent(btnKupDedinu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDediny1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vykreslovacObce2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tehlaDedina1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(drevoDedina1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(obilieDedina1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ovcaDedina1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                                        .addComponent(btnKupMesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vykreslovacObce1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlHrac1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(obilie2mesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(obilie1mesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlHrac1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kamen3mesto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamen2mesto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kamen1mesto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap())))
        );

        btnPrepniHraca.setText("Prepni hraca");
        btnPrepniHraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepniHracaActionPerformed(evt);
            }
        });

        pnlHrac2.setPreferredSize(new java.awt.Dimension(420, 328));
        this.pnlHrac2 = new HracPanel(this.hrac2, this,        
            this.lblDrevo2, this.lblTehla2, this.lblObilie2, this.lblOvca2, this.lblKamen2,   
            this.lblCesty2, this.lblDediny2, this.lblMesta2,     
            this.btnKupCestu2, this.btnKupDedinu2, this.btnKupMesto2,           
            this.lblPocetBodov2);

        lblDrevo2.setText("jLabel1");

        lblTehla2.setText("jLabel2");

        lblObilie2.setText("jLabel3");

        lblOvca2.setText("jLabel4");

        lblKamen2.setText("jLabel5");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnKupCestu2.setText("Kup cestu");
        btnKupCestu2.setMaximumSize(new java.awt.Dimension(100, 30));
        btnKupCestu2.setMinimumSize(new java.awt.Dimension(100, 30));
        btnKupCestu2.setPreferredSize(new java.awt.Dimension(100, 30));
        btnKupCestu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKupCestu2ActionPerformed(evt);
            }
        });

        btnKupDedinu2.setText("Kup dedinu");
        btnKupDedinu2.setMaximumSize(new java.awt.Dimension(100, 30));
        btnKupDedinu2.setMinimumSize(new java.awt.Dimension(100, 30));
        btnKupDedinu2.setPreferredSize(new java.awt.Dimension(100, 30));
        btnKupDedinu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKupDedinu2ActionPerformed(evt);
            }
        });

        btnKupMesto2.setText("Kup mesto");
        btnKupMesto2.setMaximumSize(new java.awt.Dimension(100, 30));
        btnKupMesto2.setMinimumSize(new java.awt.Dimension(100, 30));
        btnKupMesto2.setPreferredSize(new java.awt.Dimension(100, 30));
        btnKupMesto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKupMesto2ActionPerformed(evt);
            }
        });

        lblCesty2.setText("jLabel1");

        lblDediny2.setText("jLabel2");

        lblMesta2.setText("jLabel3");

        javax.swing.GroupLayout pnlHrac2Layout = new javax.swing.GroupLayout(pnlHrac2);
        pnlHrac2.setLayout(pnlHrac2Layout);
        pnlHrac2Layout.setHorizontalGroup(
            pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHrac2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHrac2Layout.createSequentialGroup()
                        .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmpOvca2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmpDrevo2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(cmpTehla2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmpObilie2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObilie2)
                            .addComponent(lblOvca2)
                            .addComponent(lblDrevo2)
                            .addComponent(lblTehla2)))
                    .addGroup(pnlHrac2Layout.createSequentialGroup()
                        .addComponent(cmpKamen2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKamen2)))
                .addGap(38, 38, 38)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator5)
                    .addGroup(pnlHrac2Layout.createSequentialGroup()
                        .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHrac2Layout.createSequentialGroup()
                                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlHrac2Layout.createSequentialGroup()
                                        .addComponent(vykreslovacObce4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDediny2))
                                    .addComponent(btnKupDedinu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlHrac2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(ovcaDedina2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHrac2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(drevoDedina2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tehlaDedina2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(obilieDedina2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlHrac2Layout.createSequentialGroup()
                                .addComponent(btnKupMesto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(obilie1mesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(obilie2mesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHrac2Layout.createSequentialGroup()
                                .addComponent(vykreslovacObce3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMesta2)
                                .addGap(16, 16, 16)
                                .addComponent(kamen1mesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kamen2mesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kamen3mesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHrac2Layout.createSequentialGroup()
                                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlHrac2Layout.createSequentialGroup()
                                        .addComponent(vykreslovacCesty2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCesty2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnKupCestu2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(drevoCesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tehlaCesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHrac2Layout.setVerticalGroup(
            pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHrac2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDrevo2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cmpDrevo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTehla2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cmpTehla2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblObilie2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cmpObilie2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOvca2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cmpOvca2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmpKamen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKamen2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlHrac2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(pnlHrac2Layout.createSequentialGroup()
                        .addComponent(btnKupCestu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drevoCesta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vykreslovacCesty2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCesty2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tehlaCesta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlHrac2Layout.createSequentialGroup()
                                .addComponent(btnKupDedinu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vykreslovacObce4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDediny2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlHrac2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tehlaDedina2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drevoDedina2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ovcaDedina2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(obilieDedina2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHrac2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnKupMesto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vykreslovacObce3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlHrac2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(obilie1mesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(obilie2mesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(pnlHrac2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(kamen1mesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kamen2mesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kamen3mesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        lblPocetBodov1.setText("jLabel1");

        lblPocetBodov2.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlHrac1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPocetBodov1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnHodKockou, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblSucetHodov, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrepniHraca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPocetBodov2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlHrac2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(pnlHrac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPocetBodov1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHodKockou, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSucetHodov, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrepniHraca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(pnlHrac2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPocetBodov2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metoda sa vykona, ked sa klikne na tlacidlo HodKockou, posiela kocke spravu vykonajAkciu()
     * @param evt 
     */
    private void btnHodKockouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHodKockouActionPerformed
        this.kocka.vykonajAkciu(this.hracNaRade, this.hracNehrajuci, this.tah, this, this.lblSucetHodov);
    }//GEN-LAST:event_btnHodKockouActionPerformed

    private void lyrHraciaPlochaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lyrHraciaPlochaMouseEntered
        
    }//GEN-LAST:event_lyrHraciaPlochaMouseEntered

    /**
     * metoda sa vykona, ked sa klikne na plochu pre pridavanie, posiela jej spravu o vykonani akcie
     * @param evt parameter metody, ziskavam z neho bod, na ktory hrac klikol
     */
    private void lyrPlochaPrePridavanieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lyrPlochaPrePridavanieMouseClicked
        Point point = evt.getPoint();  
        this.lyrPlochaPrePridavanie.vykonajAkciu(this.hracNaRade, this.tah, point, this);
    }//GEN-LAST:event_lyrPlochaPrePridavanieMouseClicked

    /**
     * metoda sa vykona, ked sa klikne na tlacidlo KupDedinu1, posiela hracovmu panelu spravu
     * @param evt 
     */
    private void btnKupDedinu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKupDedinu1ActionPerformed
        this.pnlHrac1.kupDedinu();
    }//GEN-LAST:event_btnKupDedinu1ActionPerformed

    /**
     * metoda sa vykona, ked sa klikne na tlacidlo KupCestu1, posiela hracovmu panelu spravu
     * @param evt 
     */
    private void btnKupCestu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKupCestu1ActionPerformed
        this.pnlHrac1.kupCestu();
    }//GEN-LAST:event_btnKupCestu1ActionPerformed

    /**
     * metoda sa vykona, ked sa klikne na tlacidlo KupMesto1, posiela hracovmu panelu spravu
     * @param evt 
     */
    private void btnKupMesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKupMesto1ActionPerformed
        this.pnlHrac1.kupMesto();
    }//GEN-LAST:event_btnKupMesto1ActionPerformed

    /**
     * metoda prepina hraca na kocni tahu, vykona sa ked sa klikne na tlacidlo PrepniHraca
     * @param evt 
     */
    private void btnPrepniHracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepniHracaActionPerformed
        this.tah++;
        
        HracPanel hracNaRadePanel = (HracPanel)this.hracNaRade.getPanel();
        HracPanel hracNehrajuciPanel = (HracPanel)this.hracNehrajuci.getPanel();
        
        hracNaRadePanel.setStlacitelnostKupovacichTlacidiel(false);
        hracNehrajuciPanel.setStlacitelnostKupovacichTlacidiel(false);
        hracNaRadePanel.zneviditelniPocitadlaSurovin();
        hracNaRadePanel.zneviditelniPocitadlaPrislusenstva();
        
        if (this.hracNaRade.equals(this.hrac1)) {
            this.hracNaRade = this.hrac2;
            this.hracNehrajuci = this.hrac1;
        } else {
            this.hracNaRade = this.hrac1;
            this.hracNehrajuci = this.hrac2;
        }
        this.kocka.setJePrvyHod(true);
        this.lblSucetHodov.setText("Zatiaľ si nehodil");
        JOptionPane.showMessageDialog(this, "Na rade je " + this.hracNaRade.getMeno());
        JOptionPane.showMessageDialog(this, this.hracNaRade.getMeno() + " hádže kockou.");
    }//GEN-LAST:event_btnPrepniHracaActionPerformed

    /**
     * metoda sa vykona, ked sa klikne na tlacidlo KupCestu2, posiela hracovmu panelu spravu
     * @param evt 
     */
    private void btnKupCestu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKupCestu2ActionPerformed
        this.pnlHrac2.kupCestu();
    }//GEN-LAST:event_btnKupCestu2ActionPerformed

    /**
     * metoda sa vykona, ked sa klikne na tlacidlo KupDedinu2, posiela hracovmu panelu spravu
     * @param evt 
     */
    private void btnKupDedinu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKupDedinu2ActionPerformed
        this.pnlHrac2.kupDedinu();
    }//GEN-LAST:event_btnKupDedinu2ActionPerformed

    /**
     * metoda sa vykona, ked sa klikne na tlacidlo KupMesto2, posiela hracovmu panelu spravu
     * @param evt 
     */
    private void btnKupMesto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKupMesto2ActionPerformed
        this.pnlHrac2.kupMesto();
    }//GEN-LAST:event_btnKupMesto2ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHodKockou;
    private javax.swing.JButton btnKupCestu1;
    private javax.swing.JButton btnKupCestu2;
    private javax.swing.JButton btnKupDedinu1;
    private javax.swing.JButton btnKupDedinu2;
    private javax.swing.JButton btnKupMesto1;
    private javax.swing.JButton btnKupMesto2;
    private javax.swing.JButton btnPrepniHraca;
    private osadnicizkatanu.surovina.VykreslovacSuroviny cmpDrevo1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny cmpDrevo2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny cmpKamen1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny cmpKamen2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny cmpObilie1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny cmpObilie2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny cmpOvca1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny cmpOvca2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny cmpTehla1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny cmpTehla2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny drevoCesta1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny drevoCesta2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny drevoDedina1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny drevoDedina2;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private osadnicizkatanu.surovina.VykreslovacSuroviny kamen1mesto1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny kamen1mesto2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny kamen2mesto1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny kamen2mesto2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny kamen3mesto1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny kamen3mesto2;
    private javax.swing.JLabel lblCesty1;
    private javax.swing.JLabel lblCesty2;
    private javax.swing.JLabel lblDediny1;
    private javax.swing.JLabel lblDediny2;
    private javax.swing.JLabel lblDrevo1;
    private javax.swing.JLabel lblDrevo2;
    private javax.swing.JLabel lblKamen1;
    private javax.swing.JLabel lblKamen2;
    private javax.swing.JLabel lblMesta1;
    private javax.swing.JLabel lblMesta2;
    private javax.swing.JLabel lblObilie1;
    private javax.swing.JLabel lblObilie2;
    private javax.swing.JLabel lblOvca1;
    private javax.swing.JLabel lblOvca2;
    private javax.swing.JLabel lblPocetBodov1;
    private javax.swing.JLabel lblPocetBodov2;
    private javax.swing.JLabel lblSucetHodov;
    private javax.swing.JLabel lblTehla1;
    private javax.swing.JLabel lblTehla2;
    private osadnicizkatanu.platno.HraciaPlocha lyrHraciaPlocha;
    private osadnicizkatanu.platno.HraciaPlochaCisla lyrPlochaCisla;
    private osadnicizkatanu.platno.PlochaPrePridavanie lyrPlochaPrePridavanie;
    private osadnicizkatanu.surovina.VykreslovacSuroviny obilie1mesto1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny obilie1mesto2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny obilie2mesto1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny obilie2mesto2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny obilieDedina1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny obilieDedina2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny ovcaDedina1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny ovcaDedina2;
    private osadnicizkatanu.hra.HracPanel pnlHrac1;
    private osadnicizkatanu.hra.HracPanel pnlHrac2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny tehlaCesta1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny tehlaCesta2;
    private osadnicizkatanu.surovina.VykreslovacSuroviny tehlaDedina1;
    private osadnicizkatanu.surovina.VykreslovacSuroviny tehlaDedina2;
    private osadnicizkatanu.hra.prislusenstvo.VykreslovacCesty vykreslovacCesty1;
    private osadnicizkatanu.hra.prislusenstvo.VykreslovacCesty vykreslovacCesty2;
    private osadnicizkatanu.hra.prislusenstvo.VykreslovacObce vykreslovacObce1;
    private osadnicizkatanu.hra.prislusenstvo.VykreslovacObce vykreslovacObce2;
    private osadnicizkatanu.hra.prislusenstvo.VykreslovacObce vykreslovacObce3;
    private osadnicizkatanu.hra.prislusenstvo.VykreslovacObce vykreslovacObce4;
    // End of variables declaration//GEN-END:variables

    /**
     * metoda nastavuje aktivitu plochy (pre pridavanie) pre pridanie cesty
     * @param ako ci ma byt aktivna
     */
    public void setPlochaPreCesty(boolean ako) {
        this.lyrPlochaPrePridavanie.setPlochaPreCesty(ako);
    }
    
    /**
     * metoda nastavuje aktivitu plochy (pre pridavanie) pre pridanie dediny
     * @param ako ci ma byt aktivna
     */
    public void setPlochaPreDediny(boolean ako) {
        this.lyrPlochaPrePridavanie.setPlochaPreDediny(ako);
    }
    
    /**
     * metoda nastavuje aktivitu plochy (pre pridavanie) pre pridanie mesta
     * @param ako ci ma byt aktivna
     */
    public void setPlochaPreMesta(boolean ako) {
        this.lyrPlochaPrePridavanie.setPlochaPreMesta(ako);
    }
}
