package osadnicizkatanu.uvod;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import osadnicizkatanu.hra.Hrac;
import osadnicizkatanu.platno.HlavneOkno;

/**
 * Trieda tvoriaca uvodne okno hry
 * @author Adam
 */
public class UvodneOkno extends javax.swing.JFrame {

    /**
     * Konstruktor vytvori nove uvodne okno
     */
    public UvodneOkno() {
        this.nacitajPozadie();
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVitajte = new javax.swing.JLabel();
        this.lblVitajte.setFont(new Font("Serif", Font.BOLD, 30));
        jPanel1 = new javax.swing.JPanel();
        lblDruhyHrac = new javax.swing.JLabel();
        lblPrvyHrac = new javax.swing.JLabel();
        txtPrvyHrac = new javax.swing.JTextField();
        btnZacniHru = new javax.swing.JButton();
        lblNapisteMena = new javax.swing.JLabel();
        this.lblNapisteMena.setFont(new Font("Serif", Font.ROMAN_BASELINE, 20));
        txtDruhyHrac = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Osadnici z Katanu ");
        setMaximumSize(new java.awt.Dimension(450, 332));
        setMinimumSize(new java.awt.Dimension(450, 322));
        setPreferredSize(new java.awt.Dimension(450, 322));
        setResizable(false);

        lblVitajte.setBackground(new Color(240, 95, 45, 200));
        lblVitajte.setText("Vitajte v hre Osadníci z Katanu");
        lblVitajte.setOpaque(true);

        jPanel1.setBackground(new Color(240, 95, 45, 200));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDruhyHrac.setText("Druhý hráč");

        lblPrvyHrac.setText("Prvý hráč");

        btnZacniHru.setText("Začni hru");
        btnZacniHru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZacniHruActionPerformed(evt);
            }
        });

        lblNapisteMena.setText("Tu zvoľte mená hráčov");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblPrvyHrac, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPrvyHrac, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblDruhyHrac, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDruhyHrac, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblNapisteMena, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnZacniHru, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblNapisteMena, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrvyHrac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrvyHrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDruhyHrac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDruhyHrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnZacniHru)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVitajte, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVitajte, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metoda sa vyvola, ked hrac klikne na tlacidlo zacniHru, vytvori sa instancia hlavneho okna a teda zacne sa hra
     * @param evt 
     */
    private void btnZacniHruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZacniHruActionPerformed
        String hrac1 = this.txtPrvyHrac.getText();
        String hrac2 = this.txtDruhyHrac.getText();
        
        new HlavneOkno(new Hrac(hrac1, "modra"), new Hrac(hrac2, "cervena"));
        this.setVisible(false);
    }//GEN-LAST:event_btnZacniHruActionPerformed

    /**
     * Main metoda, ktora vytvara uvodne okno
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UvodneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UvodneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UvodneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UvodneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UvodneOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZacniHru;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDruhyHrac;
    private javax.swing.JLabel lblNapisteMena;
    private javax.swing.JLabel lblPrvyHrac;
    private javax.swing.JLabel lblVitajte;
    private javax.swing.JTextField txtDruhyHrac;
    private javax.swing.JTextField txtPrvyHrac;
    // End of variables declaration//GEN-END:variables

    /**
     * metoda nacita obrazok tvoriaci pozadie uvodnej obrazovky
     */
    private void nacitajPozadie() {        
        try {
            Image obrazok = ImageIO.read(this.getClass().getResource("/OzK_uvodnaObrazovkaPozadie.jpg"));
            //Image obrazok = ImageIO.read(new File("img/OzK_uvodnaObrazovkaPozadie.jpg"));
            this.setContentPane(new Pozadie(obrazok));
        } catch (IOException ex) {
            System.out.println("pozadie neexistuje");
        }
    }

}
